In [2]:
from IPython.display import clear_output # clear_output() 으로 아웃풋 제거 가능
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import sklearn as sk

%matplotlib inline
%config InlineBackend.figure_formats = {'png','retina'}

import matplotlib as mpl
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D

import seaborn as sns
sns.set()
sns.set_style("whitegrid")
sns.set_color_codes()

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)

#한글폰트 적용
from matplotlib import font_manager, rc
font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)
#음수처리
mpl.rcParams['axes.unicode_minus'] = False

# ■ Konlpy의 Okt(twitter)로 토크나이징하기 (연습)
- https://ratsgo.github.io/natural%20language%20processing/2017/03/08/word2vec/ 텍스트마이닝으로 유명한 블로그
- https://github.com/lovit/soy/tree/master/tutorials/soy 쓸만한 토크나이져

In [3]:
# Konlpy의 Okt(twitter)로 토크나이징하기
from konlpy.corpus import kolaw
from konlpy.tag import *
import konlpy

In [4]:
kolaw.fileids()
c = kolaw.open('constitution.txt').read()
print(c[:100])

['constitution.txt']

대한민국헌법

유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로 건립된 대한민국임시정부의 법통과 불의에 항거한 4·19민주이념을 계승하고, 조국의 민주개혁과 평화적 통일의


In [14]:
kkma = Kkma()
komoran = Komoran()
hanna = Hannanum()

openkoreantext = Okt()

In [257]:
ex_text = "아이폰 기다리다 지쳐 애플공홈에서 언락폰질러버렸나 6+ 128기가실벜ㅋ"
# Mecab.nouns(phrase=c[:100])
# kkma.nouns(c[:100])
# komoran.nouns(c[:100])
# openkoreantext.nouns(c[:100])

# hanna.morphs(ex_text)
# hanna.nouns(ex_text)
# kkma.nouns(ex_text)
# openkoreantext.morphs(ex_text)
# openkoreantext.pos(ex_text)
openkoreantext.pos(ex_text, norm=True, stem=True)

[('아이폰', 'Noun'),
 ('기다리다', 'Verb'),
 ('지치다', 'Verb'),
 ('애플', 'Noun'),
 ('공홈', 'Noun'),
 ('에서', 'Josa'),
 ('언', 'Modifier'),
 ('락폰', 'Noun'),
 ('지르다', 'Verb'),
 ('버리다', 'Verb'),
 ('6', 'Number'),
 ('+', 'Punctuation'),
 ('128', 'Number'),
 ('기', 'Noun'),
 ('가', 'Josa'),
 ('실버', 'Noun'),
 ('ㅋ', 'KoreanParticle')]

# ■ DB에서 댓글정보 가져오기

In [3]:
import sqlalchemy ,pickle
# from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy import *
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

# import MySQLdb
from sqlalchemy import create_engine

In [4]:
import getpass
myid = getpass.getpass("input DB id : ")
mypw = getpass.getpass("input DB pw : ")
# 유니코드? 특수문자들도 갈 수 있도록 utf8mb4로 설정
SQLALCHEMY_DATABASE_URI = 'mysql://'+myid+':'+mypw+'@rds-mysql.cmbehnf2vcrh.ap-northeast-2.rds.amazonaws.com/Webtoon?charset=utf8mb4'

input DB id : ········
input DB pw : ········


In [5]:
engine = create_engine(SQLALCHEMY_DATABASE_URI,convert_unicode=True)#encoding='utf-8')
connectDB = engine.connect()

In [6]:
df_info = pd.read_sql_table('info_duple',connectDB) 
df_chapter = pd.read_sql_table('chapters_final',connectDB) 

#### DB쿼리로 가져오기 연습

In [ ]:
#이건 테이블 전체를 가져오는건데... 이건 아무래도 아니지??
# raw_df = pd.read_sql_table('table_name',connectDB)

# 그래서 쿼리를 써서 가져올것이다. 아래는 예제이고~
# query = "SELECT * FROM comments_duple WHERE Region = ? and FeatureName = ? and NewUser =?"
# region = 'US'
# feature = 'tall'
# newUser = 'john'
# raw_df = pd.read_sql_query(query, connectDB, params=(region, feature , newUser))


#이게 진퉁 like % 써서 특정 단어가 들어간 데이터를 찾으려면 파이썬에서는 %%로 써야 %로 인식된다는점 참고~!
# query = "SELECT * FROM comments_duple WHERE daumName like '%%꽃%%' limit "
# username = 

In [ ]:
query = "SELECT * FROM comments_duple WHERE articleId = 50137"# limit " #50137회차의 모든 댓글 불러오기
# limits = 5000
raw_df = pd.read_sql_query(query, connectDB)#, params=[username,limits])
raw_df.tail()

#### 텍스트 토크나이징

In [ ]:
# 텍스트 토크나이징 테스트
posls = []
for i,row in raw_df.iterrows():
    print(i,"------------------ 글자길이 :",len(row['content']))
    print(row['content'])
    for text in openkoreantext.pos(row['content']):
        posls.append(text)

In [94]:
# 토큰갯수 조건걸어서 세기
a = pd.DataFrame(posls,columns=["name","pos"])
a['count'] = 1
a.tail(5)
temp = a.groupby(["name","pos"],as_index=False).agg(np.sum).sort_values("count",ascending=False).reset_index(drop=True)
temp[(temp['pos']!='Josa')&(temp['pos']!='Punctuation')&(temp['pos']!='KoreanParticle')]

name          pos  count
11080   !!!  Punctuation      1
11081    작가         Noun      1
11082     님       Suffix      1
11083  감사해요         Verb      1
11084   !!!  Punctuation      1

name          pos  count
0         피  Exclamation    344
1        인형         Noun    215
2         님       Suffix    200
3        작가         Noun    194
4        \n      Foreign    147
17       브리         Noun     70
18       너무       Adverb     67
19       7월       Number     64
21        3       Number     63
22       후기         Noun     61
24        꼭         Noun     52
28        ♡      Foreign     42
29        때         Noun     39
30        저         Noun     39
34       웹툰         Noun     36
36     기다리고         Verb     35
37       주행         Noun     34
38        제         Noun     34
39        정         Noun     34
40       헬로         Noun     34
45      무조건         Noun     31
49      단행본         Noun     29
50        잘         Verb     29
52       댓글         Noun     28
53    기다릴게요         Verb     28
55       정말         Noun     27
56       사랑         Noun     27
57       진짜         Noun     27
59       펀딩         Noun     26
60       다시         Noun     25
...     ...          ...    ...
3071    베스트         Noun      1
3072      별         Noun      1
3073     별로         Noun      1
3074     보게         Verb      1
3075   번했는데    Adjective      1
3076    보게되         Verb      1
3077     보겟         Verb      1
3078   보겠구나         Verb      1
3079   보겠네요         Verb      1
3080  보겠습니다         Verb      1
3081      ✨      Foreign      1
3082   번했어요    Adjective      1
3083   번하면서    Adjective      1
3084    발키리         Noun      1
3085     배려         Noun      1
3086     밝게         Verb      1
3087    밝혀요         Verb      1
3088      밤         Noun      1
3089     방금         Noun      1
3090      배         Noun      1
3091     배경         Noun      1
3092     뱃속         Noun      1
3093     번만         Noun      1
3094  버렸습니다         Verb      1
3095  버릴거에요         Verb      1
3096     버세         Noun      1
3097     버텨         Verb      1
3098   버틸게요         Verb      1
3099      ❣      Foreign      1
3100      븅         Noun      1

[2776 rows x 3 columns]

In [ ]:
df_info
df_chapter

# ■ 회차별 댓글 자동 토크나이징 ==> 회차별, 웹툰별 자료 생성==>DB전송
- 댓글마다 추천/비추천, 베댓 시스템이 존재한다
    - 따라서 댓글마다 토크나이징을 할때 해당 댓글의 추천 비추천 배댓을 수치화한 알고리즘을 적용하여 회차별 토큰마다 가중치를 준다.
- **DB화 조건**
    - 회차별DB에 전손될 토큰은 그 수가 해당웹툰회차 댓글수의 0.5%보다 많이 있어야 한다.
    - 전체웹툰DB에 전송될 토큰은 그 수가 전체 웹툰 댓글수의 0.1%보다 많이 있어야 한다.

In [177]:
# 웹툰 아이디 리스트 호출 및 생성
wbt_idls = df_info["id"].values
# wbt_idls

766

In [244]:
# 총 토크나이즈드 댓글 모음
idx = 631
error = []

In [246]:
# 리팩토링 및 각 웹툰의 전체 회차댓글들 토크나이징 
# 총 웹툰의 수 766
import time
# 텍스트 토크나이징 # 현재 진행된 회차 ~ 25
for wbt_id in wbt_idls[631:766]:
    clear_output()
    comment_cnt = 0 # 코멘트 갯수
    wbt_total_txt= pd.DataFrame(columns=["wbt_id","chapter_id","name","pos","count","subcnt","chap_comt_prob"]) #회차별 댓글
    
    print("현재 index",idx,"웹툰이름 :",df_info[df_info['id']==wbt_id]['title'].values[0])
    
    #챕터별 댓글정보 가져오기
    for i,chapt_row in df_chapter[df_chapter['wbt_id']==wbt_id].iterrows():
        
        print("웹툰id:",chapt_row["wbt_id"],"//챕터:",chapt_row["title"]," 전체회차중",i,"번째 진행중 ", end="")
        posls = [] #토큰리스트 저장용 
        recommend = [] #토큰이 있었던 댓글의 추천수 저장용
        dislike = [] #토큰이 있었던 댓글의 반대수 저장용
        best = [] #토큰이 있었던 댓글의 베스트댓글여부 저장용
        query = "SELECT * FROM comments_duple WHERE articleId = "+str(chapt_row['id'])
        print("connecting server...",end="")
        try:
            raw_df = pd.read_sql_query(query, connectDB)
        except:
            print("connection fail... try reconnecting...",end="")
            connectDB = engine.connect()
            raw_df = pd.read_sql_query(query, connectDB)
        print(" success!! now tokenizing...")
        for j,row in raw_df.iterrows():
            if j % 25 == 0:
                print(j,"번째 댓글 --- 글자길이 :",len(row['content']),end="\r")## 이거 한줄만 바꾸기 위해 마지막에 커서를 처음으로 옮겨주는 end방식
#                 print("내용 :",row['content'][:15], end="\r")
            for text in openkoreantext.pos(row['content']):
                posls.append(text)
                recommend.append(row['recommendCount'])
                dislike.append(row['disagreeCount'])
                best.append(row['isBest'])
        comment_cnt += j # 해당 회차의 총 댓글수 세기
        
        a = pd.DataFrame(posls,columns=["name","pos"])
        b = pd.DataFrame(columns=["recommend","dislike","best"]) # 알고리즘 계산용 DF
        a["wbt_id"] = wbt_id
        a["chapter_id"] = chapt_row["id"]
        a["subcnt"] = j
        a['count'] = 1
        
        #추천/비추천/베스트댓글 영향도 계산 알고리즘 적용칼럼 생성-----------
        b["recommend"] = recommend
        b["dislike"] = dislike
        b["best"] = best
        a['algo_count'] = (b['recommend']-b['dislike'])*(b["best"]+1)
        
        
        temp = a.groupby(["wbt_id","chapter_id","name","pos","subcnt"],as_index=False).agg(np.sum).sort_values("count",ascending=False).reset_index(drop=True)
        if j != 0:
            temp["chap_comt_prob"] = temp['count']/j
        else:
            temp["chap_comt_prob"] = 0
        wbt_total_txt = wbt_total_txt.append(temp, ignore_index=True)

    #댓글정보 DB로 전송
    wbt_total_txt.head()
    
    print("Sending Data to RDS server...",end="")
# 회차별 댓글 토큰정보 전송
# notice! : 여기서 회차별 텍스트토큰은 회차별 총 댓글수 대비해서 0.5%이상이 충족되어야만 db데이터로 전송됨
    final_db_send = wbt_total_txt[wbt_total_txt['chap_comt_prob']>=0.005].copy()                                         
    final_db_send.to_sql("txt_token_by_chapter", engine, if_exists="append")
    
# 웹툰별 댓글 토큰정보 전송
# notice! : 여기서 웹툰별 텍스트토큰은 웹툰별 총 댓글수 대비해서 0.1%이상이 충족되어야만 db데이터로 전송됨
    temp = wbt_total_txt[["wbt_id","name","pos","count","algo_count"]].copy()
    temp['count'] = temp['count'].astype(int)
    final_wbtDB_send = temp.groupby(["wbt_id","name","pos"],as_index=False).agg(np.sum).sort_values("count",ascending=False).reset_index(drop=True)
#     final_wbtDB_send.head()
    final_wbtDB_send['wbt_comt_prob'] = final_wbtDB_send['count']/comment_cnt
    final_wbtDB_send['comment_cnt'] = comment_cnt
    final_wbtDB_send = final_wbtDB_send[final_wbtDB_send['wbt_comt_prob']>=0.001]                                         
    final_wbtDB_send.to_sql("txt_token_by_webtoon", engine, if_exists="append")
    
    print("success!")
    idx += 1
    time.sleep(2)
print("Works all done!!")

현재 index 765 웹툰이름 : 여기 고수 추가요!
웹툰id: 1222 //챕터: 프롤로그  전체회차중 43094 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 1화  전체회차중 43095 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 2화  전체회차중 43096 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 3화  전체회차중 43097 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 4화  전체회차중 43098 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 5화  전체회차중 43099 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 6화  전체회차중 43100 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 7화  전체회차중 43101 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 8화  전체회차중 43102 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 9화  전체회차중 43103 번째 진행중 connecting server... success!! now tokenizing...
웹툰id: 1222 //챕터: 10화  전체회차중 43104 번째 진행중 connecting server... success!! now t

algo_count  chap_comt_prob chapter_id count name          pos subcnt wbt_id
0      3415.0        0.241722      31752   219    .  Punctuation    906   1222
1      4658.0        0.211921      31752   192    이         Josa    906   1222
2      3403.0        0.207506      31752   188  ...  Punctuation    906   1222
3      5884.0        0.196468      31752   178   ..  Punctuation    906   1222
4      3223.0        0.182119      31752   165    가         Josa    906   1222

Sending Data to RDS server...success!
Works all done!!


---
# ◆ 텍스트 처리툴(scikit) 사용 연습(유사도 검색 위주)

## Tfidf와 커널 사용연습

In [319]:
from konlpy.tag import *

openkoreantext = Okt()

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

# tokenizer : 문장에서 색인어 추출을 위해 명사,동사,알파벳,숫자 정도의 단어만 뽑아서 normalization, stemming 처리하도록 함
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in openkoreantext.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

# 테스트 문장
rawdata = [
    '남북 고위급회담 대표단 확정..남북 해빙모드 급물살',
    '[남북 고위급 회담]장차관만 6명..판 커지는 올림픽 회담',
    
    "아이폰 기다리다 지쳐 애플공홈에서 언락폰질러버렸나 6+ 128기가실벜ㅋ",
    '문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰',
    '1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다"',
    
    '이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨'
]

In [263]:
tokenizer(rawdata[2])

['아이폰', '기다리다', '지치다', '애플', '공홈', '락폰', '지르다', '버리다', '128', '실버']

## CountVectorizer

In [311]:
#CountVectorizer

vectorize = CountVectorizer(
    tokenizer=tokenizer, 
    min_df=2    # 예제로 보기 좋게 1번 정도만 노출되는 단어들은 무시하기로 했다
                # min_df = 0.01 : 문서의 1% 미만으로 나타나는 단어 무시
                # min_df = 10 : 문서에 10개 미만으로 나타나는 단어 무시
                # max_df = 0.80 : 문서의 80% 이상에 나타나는 단어 무시
                # max_df = 10 : 10개 이상의 문서에 나타나는 단어 무시
)

# 문장에서 노출되는 feature(특징이 될만한 단어) 수를 합한 Document Term Matrix(이하 DTM) 을 리턴한다
X = vectorize.fit_transform(rawdata)

print(
    'fit_transform, (sentence {}, feature {})'.format(X.shape[0], X.shape[1])
)
# fit_transform, (sentence 5, feature 7)

print(type(X))
# <class 'scipy.sparse.csr.csr_matrix'>

print(X.toarray())

# [[0, 1, 2, 0, 0, 0, 1],
# [0, 1, 1, 0, 0, 0, 2],
# [1, 0, 0, 2, 1, 1, 0],
# [1, 0, 0, 1, 0, 0, 0],
# [0, 0, 0, 3, 1, 1, 0]]

# 문장에서 뽑아낸 feature 들의 배열
features = vectorize.get_feature_names()
df = pd.DataFrame(X.toarray(),columns=features)
df

fit_transform, (sentence 5, feature 7)
<class 'scipy.sparse.csr.csr_matrix'>
[[0 1 2 0 0 0 1]
 [0 1 1 0 0 0 2]
 [1 0 0 2 1 1 0]
 [1 0 0 1 0 0 0]
 [0 0 0 3 1 1 0]]


1987  고위  남북  대통령  동반  여사  회담
0     0   1   2    0   0   0   1
1     0   1   1    0   0   0   2
2     1   0   0    2   1   1   0
3     1   0   0    1   0   0   0
4     0   0   0    3   1   1   0

```
이제 CountVectorizer DTM에서 내가 원하는 유사한 문장을 찾아보자.

단순히 내가 원하는 문장을 search 라고 하고, search 문장이 위에서 만든 dtm 이 가지고 있는 feature 를 기준으로 어떻게 구성이 되는지 알아보고 그 feature 들이 노출되는 수의 합을 구하면 유사한 문장들을 구할 수 있다.
```

In [282]:
# 원하는 문장을 써칭하는
srch=[t for t in tokenizer('1987 관람한 대통령 인터뷰 기사') if t in features]
print(srch)
# ['1987', '대통령']

# dtm 에서 검색하고자 하는 feature만 뽑아낸다.
srch_dtm = np.asarray(X.toarray())[:, [
    # vectorize.vocabulary_.get 는 특정 feature 가 dtm 에서 가지고 있는 index값을 리턴한다
    vectorize.vocabulary_.get(i) for i in srch
]]
df = pd.DataFrame(srch_dtm,columns=srch)
df

['1987', '대통령']


1987  대통령
0     0    0
1     0    0
2     0    0
3     1    2
4     1    1
5     0    3

```
이제 각 feature의 합을 구해서 어느 문장(row)이 가장 점수가 높은지 그리고 높은 순서대로 rawdata 에서 문장을 뽑아보자
```

In [284]:
score = srch_dtm.sum(axis=1)
print(score)
# array([0, 0, 3, 2, 3], dtype=int64) 문장별 feature 합계 점수

for i in score.argsort()[::-1]:
    if score[i] > 0:
        print('{} / score : {}'.format(rawdata[i], score[i]))
        
# 이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 3
# 문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 3
# 1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 2

[0 0 0 3 2 3]
이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 3
문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 3
1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 2


```
결과를 보면 문장이 가지고 있는 feature 의 빈도수 기준으로 뽑다보니 원하는 주제와는 다른 문장이 상위에 노출되었다. 이런 CountVectorizer의 특징은 모든 feature 가 동일한 점수를 가지고 있는 관계로 주제에서 중요하지 않은 feature가 빈번히 반복되는 단어가 노출 되는 경우에는 원하는 결과를 어렵게 만들기도 한다.
```

## TfidfVectorizer

In [321]:
vectorize = TfidfVectorizer(
    tokenizer=tokenizer,
    min_df=2,
    
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)
X = vectorize.fit_transform(rawdata)

print(
    'fit_transform, (sentence {}, feature {})'.format(X.shape[0], X.shape[1])
)
# fit_transform, (sentence 5, feature 7)

print(X.toarray())

# ([[0.        , 0.40824829, 0.81649658, 0.        , 0.        , 0.        , 0.40824829],
# [0.        , 0.40824829, 0.40824829, 0.        , 0.        , 0.        , 0.81649658],
# [0.41680418, 0.        , 0.        , 0.69197025, 0.41680418, 0.41680418, 0.        ],
# [0.76944707, 0.        , 0.        , 0.63871058, 0.        , 0.        , 0.        ],
# [0.        , 0.        , 0.        , 0.8695635 , 0.34918428, 0.34918428, 0.        ]])

# 문장에서 뽑아낸 feature 들의 배열
features = vectorize.get_feature_names()
df = pd.DataFrame(X.toarray(), columns=features)
df

fit_transform, (sentence 6, feature 7)
[[ 0.          0.45329466  0.76749457  0.          0.          0.
   0.45329466]
 [ 0.          0.45329466  0.45329466  0.          0.          0.
   0.76749457]
 [ 0.          0.          0.          0.          0.          0.          0.        ]
 [ 0.44528577  0.          0.          0.63652318  0.44528577  0.44528577
   0.        ]
 [ 0.7640961   0.          0.          0.64510243  0.          0.          0.        ]
 [ 0.          0.          0.          0.78156133  0.4411133   0.4411133
   0.        ]]


1987        고위        남북       대통령        동반        여사        회담
0  0.000000  0.453295  0.767495  0.000000  0.000000  0.000000  0.453295
1  0.000000  0.453295  0.453295  0.000000  0.000000  0.000000  0.767495
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000
3  0.445286  0.000000  0.000000  0.636523  0.445286  0.445286  0.000000
4  0.764096  0.000000  0.000000  0.645102  0.000000  0.000000  0.000000
5  0.000000  0.000000  0.000000  0.781561  0.441113  0.441113  0.000000

In [288]:
# 검색 문장에서 feature를 뽑아냄
srch=[t for t in tokenizer('1987 관람한 대통령 인터뷰 기사') if t in features]
print(srch)
# ['1987', '대통령']

# dtm 에서 검색하고자 하는 feature만 뽑아낸다.
srch_dtm = np.asarray(X.toarray())[:, [
    # vectorize.vocabulary_.get 는 특정 feature 가 dtm 에서 가지고 있는 index값을 리턴한다
    vectorize.vocabulary_.get(i) for i in srch
]]

#   	1987 	대통령
# 0 	0.000000 	0.000000
# 1 	0.000000 	0.000000
# 2 	0.416804 	0.691970
# 3 	0.769447 	0.638711
# 4 	0.000000 	0.869563

score = srch_dtm.sum(axis=1)
print(score)
# array([0.         0.         1.10877443 1.40815765 0.8695635 ], dtype=int64) 문장별 feature 합계 점수

for i in score.argsort()[::-1]:
    if score[i] > 0:
        print('{} / score : {}'.format(rawdata[i], score[i]))

['1987', '대통령']
[ 0.          0.          0.          1.08180894  1.40919853  0.78156133]
1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 1.40919853348062
문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 1.08180894492714
이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 0.7815613276858536


```
결과를 보면 하나의 feature가 가지는 score가 문장별로 다르게 적용 되어 있어, 유사 문장을 추출했을때 비교적 주제에 가까운 문장들이 상위에 노출 된 것을 볼 수 있다.
```

## HashingVectorizer 

In [303]:
vectorize = HashingVectorizer(
    tokenizer=tokenizer,
    n_features=7               # 기본 feature 수를 설정하며 기본값이 2의 20승이다. 아래 예시를 위해 feature 를 7로 한정했으나, 아래 유사문장을 찾을때는 다시 n_features 주석처리 했다.
)
X = vectorize.fit_transform(rawdata)

print(X.shape)
# (5, 7)

print(X.toarray())

(5, 7)
[[ 0.33333333  0.33333333 -0.33333333  0.33333333  0.33333333  0.66666667
   0.        ]
 [ 0.          0.         -0.57735027  0.57735027  0.57735027  0.          0.        ]
 [ 0.          0.          0.          0.         -0.21821789 -0.43643578
   0.87287156]
 [ 0.          0.          0.          0.81649658  0.         -0.40824829
   0.40824829]
 [ 0.28867513  0.28867513 -0.28867513  0.28867513 -0.57735027  0.
   0.57735027]]


```
좀더 간단한 방법으로 유사 문장을 찾아보자. 다음은 문장 유사도 측정을 위해 이미 만들어진 벡터 X와 search문장 벡터를 내적해서 코사인유사도를 구하고 유사문장을 찾는 과정을 보여준다.
```

In [322]:
# search 문장 벡터
srch_vector = vectorize.transform([
    '1987 관람한 대통령 인터뷰 기사'
])

print(srch_vector.shape)
srch_vector.toarray()
features

(1, 7)


array([[ 0.7640961 ,  0.        ,  0.        ,  0.64510243,  0.        ,
         0.        ,  0.        ]])

['1987', '고위', '남북', '대통령', '동반', '여사', '회담']

In [323]:
from sklearn.metrics.pairwise import linear_kernel

# linear_kernel은 두 벡터의 dot product이다.
cosine_similar = linear_kernel(srch_vector,X).flatten()
# 위 코드는 아래와 같은 역할을 한다
# cosine_similar = (srch_vector*X.T).toarray().flatten()

print(cosine_similar)

print(cosine_similar.shape)

[ 0.          0.          0.          0.75086377  1.          0.50418711]
(6,)


In [324]:
# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
print(sim_rank_idx)

for i in sim_rank_idx:
    if cosine_similar[i] > 0 :
        print('{} / score : {}'.format(rawdata[i],cosine_similar[i]))

[4 3 5 2 1 0]
1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 1.0000000000000002
문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 0.7508637688632365
이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 0.5041871134778219


# ★Tfidf와 코사인 유사도로 특정 문자열 과 유사한 문장 검색!
# (연습 풀버전)

In [346]:
from konlpy.tag import *

openkoreantext = Okt()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

# tokenizer : 문장에서 색인어 추출을 위해 명사,동사,알파벳,숫자 정도의 단어만 뽑아서 normalization, stemming 처리하도록 함
def tokenizer(raw, pos=["Noun","Alpha","Verb","Number"], stopword=[]):
    return [
        word for word, tag in openkoreantext.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

# 테스트 문장
rawdata = [
    '남북 고위급회담 대표단 확정..남북 해빙모드 급물살',
    '[남북 고위급 회담]장차관만 6명..판 커지는 올림픽 회담',
    
    "아이폰 기다리다 지쳐 애플공홈에서 언락폰질러버렸나 6+ 128기가실벜ㅋ",
    "애플의 갑질? 아이폰 판매처를 제한하는것이 합당한가?",
    "삼성 갤럭시. 아이폰6와 정면대결 불가피",
    "갤럭시노트의 아이폰과 비교할수 없는 강력한 기능 7가지",
    "스마트폰 대란. 해외에서 언락폰을 지르는 사람들",
    "시민과 함께 찰칵! 스마트폰으로 셀카찍는 대통령",
    "스마트폰 산업 위기인데.. 대통령과 정부의 삼성때리기는 계속되는가?",
    '문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰',
    '1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다"',
    
    '이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨'
]

In [347]:
vectorize = TfidfVectorizer(
    tokenizer=tokenizer,
    min_df=1,
    
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)
X = vectorize.fit_transform(rawdata)

# print(
#     'fit_transform, (sentence {}, feature {})'.format(X.shape[0], X.shape[1])
# )
# print(X.toarray())


# 문장에서 뽑아낸 feature 들의 배열
features = vectorize.get_feature_names()

# search 문장 벡터
srch_vector = vectorize.transform([
#     '1987 관람한 대통령 인터뷰 기사',
    '갤럭시 아이폰 비교, 대통령의 스마트폰은?',
])

# print(srch_vector.shape)
# srch_vector.toarray()
# features


# linear_kernel은 두 벡터의 dot product이다.
cosine_similar = linear_kernel(srch_vector,X).flatten()
# 위 코드는 아래와 같은 역할을 한다
# cosine_similar = (srch_vector*X.T).toarray().flatten()

# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
# print(sim_rank_idx)

for i in sim_rank_idx:
    if cosine_similar[i] > 0 :
        print('{} / score : {}'.format(rawdata[i],cosine_similar[i]))

갤럭시노트의 아이폰과 비교할수 없는 강력한 기능 7가지 / score : 0.5153675295044042
삼성 갤럭시. 아이폰6와 정면대결 불가피 / score : 0.2773774247232628
시민과 함께 찰칵! 스마트폰으로 셀카찍는 대통령 / score : 0.27066487298071207
스마트폰 산업 위기인데.. 대통령과 정부의 삼성때리기는 계속되는가? / score : 0.18541294031581348
스마트폰 대란. 해외에서 언락폰을 지르는 사람들 / score : 0.14050382751801854
이명박 전 대통령과 전 대통령의 부인 김윤옥 여사, 그리고 전 대통령의 아들 이시형씨의 동반 검찰출석이 기대됨 / score : 0.1305584163530806
문재인 대통령과 대통령의 영부인 김정숙여사 내외의 동반 1987 관람 후 인터뷰 / score : 0.11907422259835522
애플의 갑질? 아이폰 판매처를 제한하는것이 합당한가? / score : 0.09437545989787822
1987 본 문 대통령.."그런다고 바뀌나? 함께 하면 바뀐다" / score : 0.09097367361429477
아이폰 기다리다 지쳐 애플공홈에서 언락폰질러버렸나 6+ 128기가실벜ㅋ / score : 0.08727022979998375


---
# ■ 텍스트 특징추출 및 유사도 추출
### 1. 장르-키워드 TF-idf 유사도 구하기
- 장르 + 소분류 + 웹툰설명을 하나의 문장으로 완성하여 그 문장을 토대로 TF-idf기반 텍스트 분석

### 2. 댓글성향 TF-IDF의 개념 변형하여 활용
- (댓글에 추천/비추천/베스트 기능이 있어서 가중치를 더하는 방식으로 활용계획)
- 텍스트 토큰 벡터화 및 유사도 파악
    1. 일부 댓글로 유사댓글 찾아보기
    2. 일부 회차 댓글토큰들로 유사 회차 및 내용 찾아보기 (문제점 댓글의 수가 현저히 다를 수 있다. 평균화 작업 필요)
- 실제 자료 테스트
    1. 회차별 특징 및 유사도 추출
    2. 웹툰별 특징 및 유사도 추출

---
![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGAFlesacryqIm5XeCpgmdNKkWO7wReeuRIVa4Lc8uugm_peMO)
# 1. 장르-키워드 TF-IDF 유사도 구하기
- 결론 : 결과를 보면 비슷한 내용이나 장르를 찾아내는데 유용한것으로 판단됨 but 항상 완벽하진 않음

In [1]:
# 일단 어디부터 실행해야 하는가?
# 일단 웹툰정보에서 장르를 다 가져오고, 웹툰 설명문도 가져오고, 웹툰 소분류도 다 가지고온다.
# 문자열로 합친다
# 토크나이징하면 어떻게 되는지 예시결과를 본다.
# 실제 TF-IDF화 하여 장르를 기반으로 찾으면 어떻게 추천되는지 확인해본다.

# 쿼리로 DB에서 가져오기
query = "SELECT * FROM comments_duple WHERE articleId = 50137"# limit " #50137회차의 모든 댓글 불러오기
# limits = 5000
raw_df = pd.read_sql_query(query, connectDB)#, params=[username,limits])
raw_df.tail()


In [12]:
texts = df_info[['id','title','intro', 'genres', 'categories']]
texts

id                title                                              intro genres              categories
0    1531  별똥별이 떨어지는 그 곳에서 기다려                     실종되는 별똥별들의 행방을 쫓는 마녀와 고양이의 이야기    판타지      동화/마녀/동물/성장드라마/스토리
1    1530               나는 달린다  육상부 유망주 채준수, 달리고 싶지만 달릴 수 없다. 푸른 하늘 끝까지 달리고 싶은...    드라마      질병/가난/학교생활/스포츠/스토리
2    1444                 우두커니                                어느 날, 아버지에게 치매가 왔다.    드라마        가족/부부/아버지/노인/스토리
3    1532                 밤의 향                                               None   None                    None
4    1346                헬로 브리          어느 날 이루어진 이상한 만남. 그러나 별 탈 없이 굴러가는 단순한 사람들    드라마       뱀파이어/술/고양이/힐링/스토리
5    1313                 나빌레라                    나이 일흔에 도전을 시작했다. 스물셋, 방황이 시작됐다.    드라마          꿈/발레/도전/희망/스토리
6    1338              이태원 클라쓰      각자의 가치관이 어우러지는 이 곳, '이태원'. 이 거리를 살아가는 그들의 이야기    드라마       청춘/술/성장드라마/연애/스토리
7    1299                 쌍갑포차  <2017 대한민국 만화대상> 우수상 수상. 늦은 밤, 낯선 곳에 나타난 의문의 포...    판타지           음식/꿈/술/갑질/스토리
8    1421                  옥탑빵         회사를 그만두고 차린 옥탑방 빵집에서 일어나는 빵냄새 고소한 우리들의 이야기    드라마       힐링/30대/빵/직장인/에피소드
9    1415           어쩌다 발견한 7월                할 수 있는 게 이것 밖에 없었어. 단지 너를 만나러 가는 것.    판타지      첫사랑/기억/연애/학교생활/스토리
10   1395                 아비무쌍              하늘의 뜻을 아니 아비는 무쌍이다. '레드스톰' 노경찬 작가의 신작    판타지      무장/성장드라마/아빠/영웅/스토리
11   1467          구리의 구리구리 컴백                     논픽션 좌충우돌, 돌아온 구리의 구리구리한 개그 일상툰     코믹       생활툰/공감/병맛/엽기/에피소드
12   1386            우리학교 김선생님         초보 교사 수지와 완벽한 교사 선우. 너무 다른 두 명의 김 선생님 이야기.    드라마   선생님/성장드라마/연애/학교생활/스토리
13   1466                 새벽날개         오토바이에 앉아 먹고, 오토바이에 기대어 사랑하고, 오토바이 타며 생각하고.    드라마     성장드라마/로드무비/삶/여행/스토리
14   1314           발자국이 녹기 전에                  가상의 조선, 세상에 의한 아픔을 가진 사람들의 사랑 이야기    드라마       연애/왕자/조선시대/기생/스토리
15   1460                노인의 집           매우 규칙적이고 성실하게 삶을 허비하는 노인의 집에 한 아이가 들어왔다.    드라마     노인/청소년/가족/성장드라마/스토리
16   1400               오리지널 씬        OCN X 강형규, 전격 콜라보레이션! OCN의 캐릭터들이 웹툰으로 부활했다.     액션       영웅/능력/히어로/초능력/스토리
17   1271                도깨비훈장                  낯선 섬, 제주도에서 만난 도깨비들이 자꾸만 나를 쫓아온다.    드라마        도깨비/귀신/가족/설화/스토리
18   1407           작약만가 : 불환곡    비단위에 내 죽음이 몰아치는구나. 아, 희라! 돌아오지 못할 자여, 반벽의 노래로다.    판타지          욕망/궁/역사/왕자/스토리
19     40               퍼펙트 게임  치열한 직장인의 삶과 야구인으로서의 삶, 대한민국 최초의 사회인 야구만화 <퍼펙트 게임>    스포츠          야구/감동/직장생활/스토리
20   1533          헬로 마이 안드로이드        내 아들이라고 주장하는 소년이 나타났다. 갑자기 시작되는 좌충우돌 SF 로맨스    판타지   타임슬립/성장드라마/연애/첫사랑/스토리
21   1225                    실                               '다시 돌아가는 거야, 당신에게로!'     순정      인연/조선시대/전생/짝사랑/스토리
22   1358                두번째 집                                 우리 집은 이런 집이 될 수 없다    드라마       가족/설레임/짝사랑/이웃/스토리
23   1356                 가랑가랑                             우리에게 선택은 언제나 어려운 일이었다.    드라마      첫사랑/친구/학교생활/학원/스토리
24   1355                  브릿지   강풀 액션만화 두번째 시즌 '브릿지'. 한국형 히어로들의 이야기는 아직 끝나지 않았다!    드라마      초능력/능력자/히어로/영웅/스토리
25   1440                  매분구        조선판 출장 메이크업 아티스트 매분구가 당대 최고의 기생으로부터 받은 부탁은?    드라마  조선시대/꽃미남/삼각관계/메이크업/스토리
26   1344               인천상륙작전                     해방에서 한국전쟁까지. 격동기를 살아간 사람들의 이야기    드라마        현대사/정치/전쟁/가난/스토리
27   1410               영웅의 변수                          슈퍼히어로를 동경하던 시골청년. 꿈을 이루다!    드라마       히어로/악당/초능력/격투/스토리
28   1405                 바리공주           무당이 되기 위한 소녀와 아내를 찾아 떠도는 남자의 조선시대 귀신 이야기    드라마         신화/귀신/전설/퇴마/스토리
29   1468          우리가 사랑하는 방법                        그녀의 마음을 얻기 위해 아이돌 덕질에 뛰어들다!     순정      짝사랑/아이돌/연애/연예인/스토리
..    ...                  ...                                                ...    ...                     ...
736   552           팬더댄스와 차봉클럽        차이니즈 봉봉클럽에 팬더댄스가 떴다?! 본격 중화요리 만화 지금부터 시작합니다     코믹         음식/중화요리/먹방/옴니버스
737  1009            공긔 엇더하니잇고                   그래, 결정했어! 나는 열심히 노력해서 공기학과를 갈거야!    스포츠   공기놀이/수능/학교생활/고등학생/스토리
738   187                 코알랄라                      먹는게 즐거운 야미 작가의 즐거운 먹부림이 시작된다!     코믹        음식/동물/요리/정보/옴니버스
739   561             얼렁뚱땅 사무소                     과

In [42]:
# 모든 웹툰의 정보텍스트를 하나로 묶어서 리스트화한다.

data_ls = []
wbt_info = []

for i,row in texts.iterrows():
#     ls.append()
    try:
#         print(row.title + "//" + row.intro + " "+ row.genres + " " + row.categories)
        data_ls.append(row.title + "//" + row.intro + "//"+ row.genres + "//" + row.categories)
        wbt_info.append({"id":row.id,"title":row.title})
    except:
        print("id",row.id,"error none type!" )
        
# 19세 웹툰의 경우 제대로 크롤링되지 않았음...25개가량 된다.

id 1532 error none type!
id 1108 error none type!
id 1297 error none type!
id 1379 error none type!
id 1298 error none type!
id 1334 error none type!
id 1110 error none type!
id 1300 error none type!
id 1384 error none type!
id 1326 error none type!
id 1503 error none type!
id 1333 error none type!
id 917 error none type!
id 1351 error none type!
id 1228 error none type!
id 1336 error none type!
id 1029 error none type!
id 911 error none type!
id 888 error none type!
id 836 error none type!
id 1264 error none type!
id 1137 error none type!
id 1437 error none type!
id 877 error none type!
id 1294 error none type!


In [51]:
from konlpy.tag import *

openkoreantext = Okt()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

# tokenizer : 문장에서 색인어 추출을 위해 명사,동사,알파벳,숫자 정도의 단어만 뽑아서 normalization, stemming 처리하도록 함
def tokenizer(raw, pos=["Noun"], stopword=[]):
    return [
        word for word, tag in openkoreantext.pos(
            raw, 
            norm=True,   # normalize 그랰ㅋㅋ -> 그래ㅋㅋ
            stem=True    # stemming 바뀌나->바뀌다
            )
            if len(word) > 1 and tag in pos and word not in stopword
        ]

# 유사도 구할 문장
rawdata = data_ls

In [75]:
# 토크나이징 테스트
test = data_ls[10]
test
pos=["Noun"]#,"Alpha","Verb","Number"]
[ (word, tag) for word, tag in openkoreantext.pos(test,norm=True,stem=True) if len(word) > 1 and tag in pos ]

'구리의 구리구리 컴백//논픽션 좌충우돌, 돌아온 구리의 구리구리한 개그 일상툰//코믹//생활툰/공감/병맛/엽기/에피소드'

[('구리', 'Noun'),
 ('컴백', 'Noun'),
 ('논픽션', 'Noun'),
 ('좌충우돌', 'Noun'),
 ('구리', 'Noun'),
 ('개그', 'Noun'),
 ('일상', 'Noun'),
 ('코믹', 'Noun'),
 ('생활', 'Noun'),
 ('공감', 'Noun'),
 ('병맛', 'Noun'),
 ('엽기', 'Noun'),
 ('에피소드', 'Noun')]

In [53]:
vectorize = TfidfVectorizer(
    tokenizer=tokenizer,
    min_df=1,
    
    sublinear_tf=True    # tf값에 1+log(tf)를 적용하여 tf값이 무한정 커지는 것을 막음
)
X = vectorize.fit_transform(rawdata)

# 문장에서 뽑아낸 feature 들의 배열
features = vectorize.get_feature_names()

In [103]:
find_text = "연애, 코믹, 개그, 학교, 순정"

In [104]:
# search 문장 벡터
srch_vector = vectorize.transform([
    find_text
])

# linear_kernel은 두 벡터의 dot product이다.
cosine_similar = linear_kernel(srch_vector,X).flatten()

# 유사한 rawdata index
sim_rank_idx = cosine_similar.argsort()[::-1]
# print(sim_rank_idx)

for i in sim_rank_idx:
    if cosine_similar[i] > 0 :
        print('{} / score : {}'.format(rawdata[i],cosine_similar[i]))

까야제맛//체이서 하준성 작가의 무한 개그본능이 살아난다!//코믹//병맛/옴니버스 / score : 0.2595404563950715
도나스 학교괴담//기묘한 학교에서 벌어지는 무시무시한 이야기//코믹//괴담/학교생활/병맛/사건사고/에피소드 / score : 0.25256962049408294
靑春도로로//세 청춘이 펼치는 DORORO한 이야기!!//코믹//청춘/열정/메시지/대안학교 / score : 0.24459869915905305
NR 뉴크앤봅//내추럴 리드미칼 외전! 뉴크와 봅의 개그 작렬!//코믹//병맛/격투/해결사/갱스터/스토리 / score : 0.2288490538366627
인생이장난2//이무기식 양아치 개그의 새로운 지평이 이제 열린다!//코믹//병맛/양아치/스토리 / score : 0.21823592718030632
구리의 구리구리 컴백//논픽션 좌충우돌, 돌아온 구리의 구리구리한 개그 일상툰//코믹//생활툰/공감/병맛/엽기/에피소드 / score : 0.21602477814480953
학교를 떠나다//행복한 고교자퇴생의 일상//드라마//자아/청소년/일탈/방황/에피소드 / score : 0.18980916653952046
결혼해도 똑같네//만화가 네온비, 캐러멜 부부 탄생! 그리고 이어지는 충격 개그 신화!//코믹//결혼생활/부부/신혼/만화가/에피소드 / score : 0.18671287345098586
킨더삼국//위촉오 삼국 유치원에서 펼쳐지는 유아 개그 버라이어티//코믹//유치원/아이들/병맛/에피소드 / score : 0.17969753594166096
지구방위연구소//지구 수호의 임무를 띤 연구소에서 펼쳐지는 개그 퍼레이드! //코믹//병맛/로봇/지구방위/옴니버스 / score : 0.17586244896729772
생존인간//학교는 나의 유일한 안식처였다. '그것'이 나타나기 전까지... //공포//살인사건/초자연/괴물/돌연변이/스토리 / score : 0.17198521323265836
피그말리온 컴플렉스//금수저 학교에 잠입한 고

In [105]:
# 제목과 유사도만 뽑기
for i in sim_rank_idx:
    if cosine_similar[i] > 0 :
        print('{} / score : {}'.format(wbt_info[i]['title'],cosine_similar[i]))

까야제맛 / score : 0.2595404563950715
도나스 학교괴담 / score : 0.25256962049408294
靑春도로로 / score : 0.24459869915905305
NR 뉴크앤봅 / score : 0.2288490538366627
인생이장난2 / score : 0.21823592718030632
구리의 구리구리 컴백 / score : 0.21602477814480953
학교를 떠나다 / score : 0.18980916653952046
결혼해도 똑같네 / score : 0.18671287345098586
킨더삼국 / score : 0.17969753594166096
지구방위연구소 / score : 0.17586244896729772
생존인간 / score : 0.17198521323265836
피그말리온 컴플렉스 / score : 0.17090655873013177
스멜스 라이크 30 스피릿 / score : 0.16875042589483516
연애싫어 / score : 0.15850517531308886
우리학교 김선생님 / score : 0.15726352931606308
0.1초의 설렘 / score : 0.15552674378121875
저녁 같이 드실래요? / score : 0.15488814037813076
날 좋아해줘 / score : 0.15389375828137689
봄, 가을 / score : 0.15259542935489845
카메라ON / score : 0.14271831726737114
나쁜 여자들 / score : 0.14220560207927674
스킬 / score : 0.14116092433592256
폐어 / score : 0.13874970402906675
아수라연 / score : 0.13686131029502538
밤의 베란다 / score : 0.13330822731494568
나의 빛나는 세계 / score : 0.13277821257384514
헌티드스쿨 원더러즈 에이스 / score :

# 결론
- 장르+소분류+웹툰 내용을 TF-idf 방식으로 유사도를 구하면 꽤 유의한 결과를 얻을 수 있다.
- 웹툰내용이 빈약한 경우 아쉬운 추천성능을 보인다. 휴먼에러로 봐야할듯
- 여기에 웹툰의 댓글텍스트를 직접 TF-idf하여 보완하면 추천 성능이 더욱 개선될 것으로 기대됨.