# 텐서플로우 튜토리얼 연습과 코드 인덱스 사전
- 튜토리얼을 제공하는 깃허브 https://github.com/golbin/TensorFlow-Tutorials

### Variable
- 텐서플로우의 플레이스 홀더와 변수의 개념을 익히자

In [5]:
import tensorflow as tf

#placeholder : 계산을 실행할 때 입력값을 받는 변수로 사용한다.
#None은 크기가 정해지지 않았음을 의미함
X = tf.placeholder(tf.float32, [None, 3])
print(X)

# X플레이스홀더에 넣을값
# 플레이스홀더에서 설정한 것처럼, 두번째 차원의 요소갯수는 3개
x_data = [[1,2,3],[4,5,6]]

#Variable : 그래프를 계산하면서 최적화 할 변수들. 이 값이 신경망을 좌우하는 값
# random_normal : 각 변수들의 초기값을 정규분포랜덤값으로 초기화
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

# 입력값과 변수들을 계산할 수식을 작성
# tf.matmul 처럼 mat*로 되어있는 함수로 행렬계산을 수행
expr = tf.matmul(X,W) + b

sess = tf.Session()
# 위에서 설정한 Variable들의 값을 초기화 해야됨
# 처음에 tf.global_variables_initializer 를 한 번 실행해야함
sess.run(tf.global_variables_initializer())

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(sess.run(W))
print("=== b ===")
print(sess.run(b))
print("===expr====")
print(sess.run(expr, feed_dict={X:x_data}))
# expr 수식에는 X라는 입력값이 필요
# 따라서 expr 실행시 이 변수에 대한 실제 입력값을 넣어줘야함

sess.close()

Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[-0.291262   -0.11953487]
 [-0.17635864  0.3196032 ]
 [ 0.96932673 -1.17966092]]
=== b ===
[[-0.78580576]
 [ 1.48390293]]
===expr====
[[ 1.47819519 -3.80511713]
 [ 5.25302219 -4.47418642]]


### basic
- 텐서플로우의 연산의 개념과 그래프를 실행하는 방법을 익힙니다.

In [3]:
import tensorflow as tf

# constant : 상수임
hello = tf.constant('Hello,TensorFlow!')
print(hello)

a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a,b) # a+b로도 쓸 수 있다.
print(c)

# 위에서 변수와 수식들을 정의했지만, 실행이 정의한 시점에서 실행되는 것이 아님. 뭔가 스파크처럼 게으른 느낌
# Session 객제와 run 메소드를 사용할 때 비로소 계산실행.
# 따라서 모델을 구성하는 것과, 실행하는 것을 분리하여 프로그램을 깔끔하게 작성할 수 있음!!!
# 그래프를 실행할 세션을 구성
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

#세션닫기
sess.close()




Tensor("Const_6:0", shape=(), dtype=string)
Tensor("Add_2:0", shape=(), dtype=int32)
b'Hello,TensorFlow!'
[10, 32, 42]
